---
title: Preprocessing data
author: Sebastian Robledo
date: "Nov 20, 2022"
format:
    html:   
        code-fold: true
---

The data is in this link
https://drive.google.com/drive/u/1/folders/1nwv_jgXQhLbLJVh0dVgh9GSzV_VUj821

```{python}
import pandas as pd
# run file from the root of the project called "groups_preprocessing.py"
%run groups_preprocessing.py
```


# Preprocessing Groups
```{python}
# create a variable called "groups_raw" from the url "https://docs.google.com/spreadsheets/d/1jNY8oEnunCXo80_BWsRtl2ejN6CQstWgs4quDNQpE8Y/export?format=csv&gid=0"
groups = "https://drive.google.com/file/d/1JNncMKuaXSwuQEp-S6wui4jiDcPGoCkU/view?usp=sharing"
groups = 'https://drive.google.com/uc?id=' + groups.split('/')[-2]
groups_raw = pd.read_csv("https://docs.google.com/spreadsheets/d/1jNY8oEnunCXo80_BWsRtl2ejN6CQstWgs4quDNQpE8Y/export?format=csv&gid=0")
# Run the function "preprocess_groups" on the variable "groups_raw"
groups = preprocessing_groups_institutions(groups_raw)
```

# Preprocessing products
```{python}
# create a variable called "groups_raw" from the url "https://docs.google.com/spreadsheets/d/1jNY8oEnunCXo80_BWsRtl2ejN6CQstWgs4quDNQpE8Y/export?format=csv&gid=0"
papers = "https://drive.google.com/file/d/1KrG-06OFCusN2JpgaqtaC4dl6sCpVaaX/view?usp=share_link"
papers = 'https://drive.google.com/uc?id=' + papers.split('/')[-2]
papers = pd.read_csv(papers)

# Group by "codigo_grupo" and count the number of values in column "titulo", save the data in dataframe called "dummy"
dummy = papers.groupby(['codigo_grupo']).size().reset_index(name='counts')
```

python code
```{python}
# from groups_raw select the columns "codigo_grupo" and "instituciones", and merge with dummy by "codigo_grupo" and "codigo del grupo"
#groups = groups_raw[['codigo_grupo', 'instituciones']].merge(dummy, on='codigo_grupo')

papers_institutions = groups_raw[['codigo del grupo', 'instituciones']].merge(dummy, left_on='codigo del grupo', right_on= 'codigo_grupo')
```
# Preprocessing researchers

```{python}
# create a variable called "researchers_raw" from the url "https://docs.google.com/spreadsheets/d/1jNY8oEnunCXo80_BWsRtl2ejN6CQstWgs4quDNQpE8Y/export?format=csv&gid=0"
researchers_url = "https://drive.google.com/file/d/143u1k6A-LZDhhSGvREzNaXYT4aUEZlGN/view?usp=share_link"
researchers_raw = 'https://drive.google.com/uc?id=' + researchers_url.split('/')[-2]
researchers = pd.read_csv(researchers_raw)
```

```{python}
dummy_1= researchers.groupby(['codigo_grupo']).size().reset_index(name='counts')

researchers_institutions = groups_raw[['codigo del grupo', 'instituciones']].merge(dummy_1, left_on='codigo del grupo', right_on= 'codigo_grupo', how='left')
```
```





```{python}
# create a variable called "researchers_raw" from the url "https://docs.google.com/spreadsheets/d/1jNY8oEnunCXo80_BWsRtl2ejN6CQstWgs4quDNQpE8Y/export?format=csv&gid=0"
researchers = "https://drive.google.com/file/d/143u1k6A-LZDhhSGvREzNaXYT4aUEZlGN/view?usp=share_link"
researchers = 'https://drive.google.com/uc?id=' + researchers.split('/')[-2]
researchers = pd.read_csv("https://docs.google.com/spreadsheets/d/1jNY8oEnunCXo80_BWsRtl2ejN6CQstWgs4quDNQpE8Y/export?format=csv&gid=0")
```

How many instituciones do we have in reserachers?
```{python}
# group the variable "instituciones" in researchers and count the number of rows in each group and sort them in descending order and save the result in a variable called "researchers_institutions"
researchers_institutions = researchers.groupby("instituciones").size().sort_values(ascending=False)
```



```{python}

```




## Reading data from papers
```{python}
url='https://drive.google.com/file/d/1KrG-06OFCusN2JpgaqtaC4dl6sCpVaaX/view?usp=share_link'
url='https://drive.google.com/uc?id=' + url.split('/')[-2]
papers = pd.read_csv(url)
```

```{python}
# Show me the first ten row of papers dataframe
papers.head(10)
```

```{python}
integrantes='https://drive.google.com/file/d/143u1k6A-LZDhhSGvREzNaXYT4aUEZlGN/view?usp=share_link'
integrantes='https://drive.google.com/uc?id=' + integrantes.split('/')[-2]
integrantes = pd.read_csv(integrantes)
```

```{python}
# read the data from this url "https://docs.google.com/spreadsheets/d/1xmA2VoQt3-cOC2b2-s3JQqt28XkS2Uz7erI2lriC-ys/export?format=csv&gid=1353066533" and remove the first row
resumen = pd.read_csv("https://docs.google.com/spreadsheets/d/1xmA2VoQt3-cOC2b2-s3JQqt28XkS2Uz7erI2lriC-ys/export?format=csv&gid=1353066533", skiprows=1)
```


